min_version = "2025.3.0"

[tools]
"cargo:node-size-analyzer" = "latest"
node = "{{ env['NODE_VERSION'] | default(value='22.14.0') }}"
pnpm = "10.7.1"

[env]
_.path = ["{{ vars.mise_bin_dir }}", "{{ vars.node_modules_bin_dir }}"]
PROJECT_NAME = "{{ config_root | basename }}"
BIN_PATH = "{{ vars.node_modules_bin_dir }}"
# NODE_ENV = "{{ env.NODE_ENV | default(value='development') }}"
# NODE_ENV = "production"
NODE_PACKAGE_MANAGER = "pnpm"

[vars]
node_modules_dir = "{{ config_root }}/node_modules"
node_modules_bin_dir = "{{ vars.node_modules_dir }}/.bin"
mise_bin_dir = "{{ config_root }}/.mise_bin"

[settings]
experimental = true

[hooks]
enter = "mise run build"

[tasks.build]
hide = true
silent = true
run = """
# mise install
mise install &> /dev/null

rm -rf {{ vars.mise_bin_dir }}
mkdir -p {{ vars.mise_bin_dir }}

# echo 'dust -d 2 --min-size 1MB --reverse ./node_modules' > {{ vars.mise_bin_dir }}/node_size_analyzer

chmod -R +x {{ vars.mise_bin_dir }}
"""

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "NODE_ENV: $NODE_ENV"
'''

[tasks.pnpm-install]
description = 'Installs dependencies with pnpm'
run = 'pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.dev]
description = 'Calls your dev script in `package.json`'
run = 'node --run dev'
depends = ['pnpm-install']
