[build]
publish = ".next"
command = "pnpm build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NODE_ENV = "production"
NODE_PACKAGE_MANAGER = "pnpm"
PROJECT_NAME = "semantic-drive"

[dev]
command = "pnpm dev"
